name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ['master']
  workflow_dispatch:
  
  jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: cassiedemo0802
          # Container registry password
          password: # default is 
          h15j7Abd2jD/HKT7Rllgtq+oWfFNSkZ5Pf9PiP4asu+ACRCQfVqZ
          login-server: cassiedemo0802.azurecr.io
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: cassiedemo0802.azurecr.io/hello-world-app:${{ github.sha }}
          file:./Dockerfile
  deployToAKS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"


      

   
